### ISSUE TITLE
Return window action buttons.

### ISSUE THREAD

**Issue by mdvmd** [mgastonportillo/gale-for-ff#4]
Hi. Is there a way to return window action button but put them on toolbar?

**Comment by mgastonportillo** [comment]
What exactly do you mean by return window action? Like when you close or move a tab? You want a mechanism to undo that?

**Comment by AryanVerma1024** [comment]
I think he means this

![image](https://github.com/mgastonportillo/gale-for-ff/assets/80571430/aac282a6-d4b8-467c-bfd0-34df269babe2)

**Comment by mgastonportillo** [comment]
Thanks for the heads up @AryanVerma1024. If that's the case, then replacing:
```css
#TabsToolbar {
  display: none !important;
  height: 0 !important;
}
```

with:
```css
#nav-bar {
	margin-top: -38px !important;
	margin-right: 138px !important;
	margin-bottom: -4px !important;
}

.tab[selected="true"] {
	visibility: collapse;
	height: 0px;
}

.tabbrowser-tab {
	visibility: collapse;
	height: 0px;
}

.tabbrowser-tab[visuallyselected="true"] {
	visibility: collapse;
	height: 0px;
}
```

would do the trick.

There are other ways to achieve this, but I don't plan to support it.

@mdvmd can you confirm that's what you meant?
